FROM ubuntu:22.04

RUN apt-get update 

RUN apt-get install -y wget git build-essential

# Enable ability to install foreign packages for cross compilation
RUN dpkg --add-architecture i386
RUN dpkg --add-architecture arm64
RUN dpkg --add-architecture riscv64

# The main archive only hosts amd64 and i386, we need to add ports for arm64 and riscv64.
RUN sed -i -e '/^deb /{h;s|deb |&[arch=amd64,i386] |p;g;s|deb http://[^ ]*|deb [arch=arm64,riscv64] http://ports.ubuntu.com/ubuntu-ports|p;d}' /etc/apt/sources.list

# Needed by llvm
RUN apt-get install --yes cmake libtinfo-dev

# Add llvm repos
RUN wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor - | tee /usr/share/keyrings/llvm-archive-keyring.gpg >/dev/null
#RUN echo 'deb [signed-by=/usr/share/keyrings/llvm-archive-keyring.gpg] http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main' | tee /etc/apt/sources.list.d/llvm.list >/dev/null
RUN echo 'deb [signed-by=/usr/share/keyrings/llvm-archive-keyring.gpg] http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main' | tee -a /etc/apt/sources.list.d/llvm.list >/dev/null
RUN echo 'deb [signed-by=/usr/share/keyrings/llvm-archive-keyring.gpg] http://apt.llvm.org/jammy/ llvm-toolchain-jammy-20 main' | tee -a /etc/apt/sources.list.d/llvm.list >/dev/null
RUN apt-get update

# Install AArch64 requirements
RUN apt-get install --yes gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
# Install RISC-V requirements
RUN apt-get install --yes gcc-riscv64-linux-gnu g++-riscv64-linux-gnu
# Install recommended packages
RUN apt-get install --yes python3 python3-pip ninja-build

#  doxygen
# Install documentation packages
# RUN apt-get install --yes graphviz latexmk texlive-xetex xindy texlive-fonts-extra
# Install CI utility packages


# Install pkg-config for dpc++ builds and locally built spir-v
RUN apt-get install --yes pkg-config

# Install spirv tools
RUN apt-get install --yes spirv-tools

# Install python packages
RUN pip install lit

RUN apt-get -y install sudo

# zstd needed for caching
RUN apt install -y zstd
RUN apt install -y ccache


# Overnight downloads only?
#RUN apt-get -y install gh
#RUN apt install -y gnupg
# ? In base ? MUST HAVE?
RUN apt install -y gcc g++
# RUN apt install -y file
# Install libhwloc-dev for dpc++ dependency
# dpc++ only
RUN apt-get install --yes libhwloc-dev:amd64 libhwloc-dev:arm64 libhwloc-dev:i386 libhwloc-dev:riscv64

#RUN pip install cmakelint colorama flake8 lit pylint requests virtualenv yapf python-gitlab distro clang-format==19.1.0
#RUN pip install virtualenv cookiecutter
RUN apt-get install --yes python3-colorama
#RUN apt-get install --yes doxygen
# MUST HAVE ? Just some e.g. lit?
# Set-up pip
#RUN update-alternatives --install /usr/bin/pip pip `which pip3` 30

# ci-tidy job only
# RUN apt-get install --yes parallel
# Install QEMU for testing cross compilation.

# Only for cross jobs
#RUN apt-get install --yes qemu-user

#RUN apt-get install --yes clang-tidy-19
# Add VulkanSDK latest package repository
#RUN wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | apt-key add -
#RUN wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.243-jammy.list https://packages.lunarg.com/vulkan/1.3.243/lunarg-vulkan-1.3.243-jammy.list
# Sync the two above package repositories
#RUN apt-get update


# Set the timezone, required to avoid hanging on input
# ENV TZ=Europe/London
# RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#RUN apt-get install -y git git-crypt wget curl jq xz-utils build-essential zlib1g-dev lsb-release libssl-dev

# Install 32-bit requirements
#RUN apt-get install --yes gcc-multilib g++-multilib libc6-dev:i386 lib32tinfo-dev
# Install Arm requirements
#RUN apt-get install --yes gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

# Install vulkan-sdk
#RUN apt-get install --yes vulkan-sdk
